### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by sabrisha** [anastasiiakuzyk/GrandHotel#1]
Hi, Anastasia! Could you please pin your .sql file to your project,  cause I've just started learning Spring Restful + mySQL services and don't really understand how to make this database correctly

**Comment by anastasiiakuzyk** [comment]
Hello, @sabrisha !
Thank you for being interested in my project, here is my hotel DB dump (.sql): [file](https://github.com/anastasiiakuzyk/GrandHotel/blob/master/-2022_09_27_14_37_30-dump.sql)
I hope this might help!

**Comment by sabrisha** [comment]
thank you so much!
